version: "3.3"

services:
  server:
    build: ../CentralIntelligence-server
    image: 016372371071.dkr.ecr.eu-central-1.amazonaws.com/centralintelligence-server
    ports:
      - 3000:3000
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
    secrets:
      - source: server-authkey
        target: authkey
  laptimes:
    build: ../CentralIntelligence-laptimes
    image: 016372371071.dkr.ecr.eu-central-1.amazonaws.com/centralintelligence-laptimes
    ports:
      - 3001:3000
    depends_on:
      - server
    environment:
      SERVER_HOST: server
      MY_HOST: laptimes
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
    secrets:
      - source: laptimes-authkey
        target: authkey
    configs:
      - source: laptimes-config
        target: /usr/src/app/config.json
    command: ["./wait-for-it.sh", "server:3000", "--", "npm", "start"]
  telegram:
    build: ../CentralIntelligence-telegram
    image: 016372371071.dkr.ecr.eu-central-1.amazonaws.com/centralintelligence-telegram
    ports:
      - 3002:3000
    depends_on:
      - server
    environment:
      SERVER_HOST: server
      MY_HOST: telegram
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
    secrets:
      - source: telegram-authkey
        target: authkey
    configs:
      - source: telegram-config
        target: /usr/src/app/config.json
    command: ["./wait-for-it.sh", "server:3000", "--", "npm", "start"]
  weather:
    build: ../CentralIntelligence-weather
    image: 016372371071.dkr.ecr.eu-central-1.amazonaws.com/centralintelligence-weather
    ports:
      - 3003:3000
    depends_on:
      - server
    environment:
      SERVER_HOST: server
      MY_HOST: weather
      FMI_APIKEY:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
    secrets:
      - source: weather-authkey
        target: authkey
    command: ["./wait-for-it.sh", "server:3000", "--", "npm", "start"]

secrets:
  server-authkey:
    file: ./server-authkey
  laptimes-authkey:
    file: ./laptimes-authkey
  telegram-authkey:
    file: ./telegram-authkey
  weather-authkey:
    file: ./weather-authkey

configs:
  laptimes-config:
    file: ./laptimes-config.json
  telegram-config:
    file: ./telegram-config.json